# Generated by Django 3.2.9 on 2021-11-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='normalpost',
            name='tag',
            field=models.ManyToManyField(related_name='blog_normalpost_related', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='subpost',
            name='tag',
            field=models.ManyToManyField(related_name='blog_subpost_related', to='blog.Tag'),
        ),
    ]
