# Generated by Django 3.2.9 on 2021-11-17 07:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='subpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
